#!/bin/sh
#
# fluxbox startup-script:
#


# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#

numlockx on &
clipit &
nm-applet &
plank &
pnmixer &
xscreensaver -no-splash &
(feh --bg-fill "$HOME/.wallpaper" ;nemo -n ) &
(sleep 10;syncthing -no-browser) &
(sleep 5; liferea) &
(sleep 5;compton)&
rofi -key-run F2 &
synapse -s &
conky &

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
