#!/bin/bash


############################################################
#                   PREPARE                                #
############################################################

hostname=$(hostname)

# Run program unless it's already running.
#run_once() {
#    if [ -z "$(pgrep -x -u "$USER" "$1")" ]; then
#              $@
#    fi
#}

############################################################
#                   AUTOSTART                              #
############################################################

xset -dpms
xscreensaver -no-splash &
xscreensaverstopper.sh &    # Stop xscreensaver when active window is fullscreen.

clipit &
pnmixer &
nm-applet &
system-config-printer-applet &
rofi -rnow -run-command "bash -c '{cmd}'" -key-run SuperL-space &
tomboy &
#keepassx  ~/Sync/keepass.kdb -min -lock &
conkyrc_cron.sh &
conky -c ~/.conkyrc_p1 &
conky -c ~/.conkyrc_p2 &
krunner &
compton &
syncthing-gtk  -m &
[ "$hostname" = "a300" ] &&  mate-power-manager &
#[ "$hostname" = "a300" ] &&  xfce4-power-manager &
#blueman-applet &
[ "$hostname" = "a300" ] && liferea -w iconified &
/usr/bin/gnome-keyring-daemon --start --components=secrets &
#pkill redshift; redshift -t 5350k:3700K -b 0.95 &

disown -a
exit 0

