#!/bin/sh


############################################################
#                   PREPARE                                #
############################################################

hostname=`hostname`

############################################################
#                   Init                                   #
############################################################

# I want my profile scripts in my X session.
. /etc/profile
. ~/.profile

#lightdm does this for me
xrdb ~/.Xresources

# Mute the anoying speaker beep
xset -b

for f in $HOME/.xsessionrc.d/*.sh; do
    if [ -r "$f" ]; then
        source "$f"
    fi
done



