#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#Bash opts.
shopt -s nocaseglob nocasematch extglob globstar 

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# My fancy prompt
fancy_prompt=yes

if [ "$fancy_prompt" = yes ]; then
    return_status="\$(
            if [[ \$? == 0 ]]; then
                echo \"\[\033[0;32m\];)\";
            else
                echo \"\[\033[0;31m\];(\";
            fi
            )\[\033[00m\]"

    # Just in case
    unset host
    [ "$SSH_CONNECTION" ] && host=@$(hostname)
    if [ "$(id -u)" -eq 0 ];then
        color="\[\033[01;31m\]"
    else
        color="\[\033[01;32m\]"
    fi

    PS1="$return_status ${debian_chroot:+($debian_chroot)}$color\u$host\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]"
    unset return_status host color
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w'
fi
unset fancy_prompt

if [ "$(id -u)" -eq 0 ];then
    PS1+='# '
else
    PS1+='$ '
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
    xterm*|rxvt*)
        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h:\W\a\]$PS1"
        ;;
    *)
        ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.sh_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -r ~/.sh_aliases ] && ! [ -f ~/.noaliases ]; then
    . ~/.sh_aliases
fi

if [ -d $HOME/.shrc.d ]; then
    for f in $HOME/.shrc.d/*.sh; do
        if [ -r "$f" ]; then
            . "$f"
        fi
    done
    unset f
fi

true

