#!/bin/sh

if [ -r /etc/.profile ]; then
    . /etc/profile
fi

if [ -r $HOME/.profile ]; then
    . $HOME/.profile
fi

if [ -r $HOME/.Xresources ]; then
    xrdb $HOME/.Xresources
fi

if [ -d $HOME/.xsessionrc.d ]; then
    for f in $HOME/.xsessionrc.d/*.sh; do
        if [ -r "$f" ]; then
            . "$f"
        fi
    done
fi



