#!/bin/zsh

# Only for interactive shells.
[[ -o interactive ]] || return

FRAMEWORK=prezto
if [ $FRAMEWORK = prezto ];then

    # Source Prezto.
    # https://github.com/sorin-ionescu/prezto
    if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
    fi

elif [ $FRAMEWORK = oh-my-zsh ];then

    # Source oh-my-zsh
    # https://github.com/robbyrussell/oh-my-zsh
    if [ -r $HOME/.oh-my-zshrc ];then
        source $HOME/.oh-my-zshrc
    fi
fi

# ctrl-u does the same it did in bash.
bindkey \^U backward-kill-line

# Add help command
autoload -U run-help
autoload run-help-git
autoload run-help-svn
autoload run-help-svk
alias help=run-help

# More Globs
setopt EXTENDED_GLOB
# 10 second wait if you do something that will delete everything. 
# I wish I'd had this before...
setopt RM_STAR_WAIT
# Disable Substituition verification
unsetopt HIST_VERIFY NO_CLOBBER AUTO_CD
# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS
# This makes cd=pushd
setopt AUTO_PUSHD
# Don't save duplicates entries in history
setopt HISTIGNOREDUPS
# Don't save history entries that start with a space
setopt HISTIGNORESPACE
# Deal with non matched * like bash does
setopt NONOMATCH

# Split white space word like bash
setopt shwordsplit

# Command prediction
if [ -r ~/.zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source ~/.zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# Workaround #
# Make zsh autocomplete respect dircolors.
# https://github.com/robbyrussell/oh-my-zsh/issues/1563
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

if [ -r ~/.sh_aliases ] && ! [ -f ~/.noaliases ]; then
    source ~/.sh_aliases
fi

if [ -d $HOME/.shrc.d ]; then
    for f in $HOME/.shrc.d/*.sh; do
        if [ -r "$f" ]; then
            . "$f"
        fi
    done
    unset f
fi

true


